packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.12.0
  "@remix-run/node": ^2.12.0
  "@remix-run/react": ^2.12.0
  "@remix-run/serve": ^2.12.0
  "@remix-run/server-runtime": ^2.12.0
  "@types/node": ^22.5.4
  react: 19.0.0-rc-d6cb4e77-20240911
  react-dom: 19.0.0-rc-d6cb4e77-20240911
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.6.2
