packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.12.1
  "@remix-run/node": ^2.12.1
  "@remix-run/react": ^2.12.1
  "@remix-run/serve": ^2.12.1
  "@types/node": ^22.7.5
  react: 19.0.0-rc-d8c90fa4-20241001
  react-dom: 19.0.0-rc-d8c90fa4-20241001
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.6.3
