packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.15.0
  "@remix-run/node": ^2.15.0
  "@remix-run/react": ^2.15.0
  "@remix-run/serve": ^2.15.0
  "@tokenami/css": ^0.0.74
  "@tokenami/dev": ^0.0.74
  "@tokenami/ds": ^0.0.74
  "@tokenami/ts-plugin": ^0.0.74
  "@types/node": ^22.10.1
  babel-plugin-react-compiler: 0.0.0-experimental-50915ff-20241206
  eslint-plugin-react-compiler: 0.0.0-experimental-50915ff-20241206
  commonality: ^0.2.63
  commonality-checks-recommended: ^0.0.40
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.1
  typescript: ^5.7.2
