packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@react-router/dev": ^7.1.3
  "@react-router/fs-routes": ^7.1.3
  "@react-router/node": ^7.1.3
  "@react-router/serve": ^7.1.3
  "@stylexjs/babel-plugin": ^0.10.1
  "@stylexjs/postcss-plugin": ^0.10.1
  "@stylexjs/stylex": ^0.10.1
  "@types/node": ^22.12.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  babel-plugin-react-compiler: 0.0.0-experimental-e4f4f9a-20250127
  commonality: ^0.2.63
  commonality-checks-recommended: ^0.0.40
  eslint-plugin-react-compiler: 0.0.0-experimental-e4f4f9a-20250127
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.1.3
  typescript: ^5.7.3
